/**
 * Templates that translate high-level POV blueprint primitives (SLA policies,
 * email channels, PLuG widget config, integrations) into structured
 * `ui_guidance_sections`. These features are not API-automatable — but they
 * are demanded in nearly every POV. The agent's contribution is to produce a
 * tight, accurate playbook the SE can follow without inventing menu paths.
 */

import { DEMO_DOC_HREF, DEVELOPER_PORTAL_HREF } from "./index.js";

export type UiGuidanceSection = {
  title: string;
  doc_links?: string[];
  steps: string[];
};

// ---------------- Prerequisites ----------------

/**
 * Single section the plan builder prepends whenever any UI-only primitive is
 * set on the blueprint. Surfaced because "access required" / "missing
 * permission" errors are a recurring pain point in DevRev support tickets.
 */
export function prerequisitesGuidance(): UiGuidanceSection {
  return {
    title: "Prerequisites — verify before running setup steps",
    doc_links: ["https://developer.devrev.ai/about/authentication"],
    steps: [
      "Confirm the DevRev user behind your PAT has the Admin role. Builder/Member roles cannot reach all Settings menus, and several integrations require Admin to install snap-ins.",
      "Confirm the PAT itself was generated by that same Admin user. PATs inherit the creator's role at the moment they were issued — escalating the user later does NOT re-scope existing tokens.",
      "If a step below returns an 'access required' or HTTP 403 error, regenerate the PAT from an Admin account and rerun `dia doctor` before retrying.",
      "Some Settings menus are scoped per-workspace; confirm you're operating in the workspace the customer will use, not your default DevRev org.",
    ],
  };
}

// ---------------- SLA policies ----------------

export type SlaSeverityTargets = {
  /** Target time-to-first-response strings, keyed by priority (p0..p3). */
  first_response?: Partial<Record<"p0" | "p1" | "p2" | "p3", string>>;
  /** Target time-to-resolution strings, keyed by priority. */
  resolution?: Partial<Record<"p0" | "p1" | "p2" | "p3", string>>;
};

export type SlaPolicyInput = {
  name: string;
  /** Optional human description (e.g. "Apply to accounts tagged Enterprise"). */
  description?: string;
  /** Apply to all accounts unless `applies_to` narrows it. */
  applies_to?: string;
  targets: SlaSeverityTargets;
  /** Optional escalation note (e.g. "Auto-escalate at 80% of target"). */
  escalation?: string;
};

const PRIORITY_LABEL: Record<string, string> = {
  p0: "p0 (blocker)",
  p1: "p1 (high)",
  p2: "p2 (medium)",
  p3: "p3 (low)",
};

function formatTargets(label: string, map?: Partial<Record<string, string>>): string | null {
  if (!map) return null;
  const parts = (["p0", "p1", "p2", "p3"] as const)
    .filter((k) => map[k])
    .map((k) => `${PRIORITY_LABEL[k]} ≤ ${map[k]}`);
  if (!parts.length) return null;
  return `${label}: ${parts.join(", ")}`;
}

export function slaGuidance(policies: SlaPolicyInput[]): UiGuidanceSection {
  const steps: string[] = [
    "Settings → SLA Policies → Create",
    "Recreate each policy below, matching the priority targets exactly.",
  ];
  for (const p of policies) {
    steps.push("");
    steps.push(`Policy: ${p.name}${p.applies_to ? ` (applies to ${p.applies_to})` : ""}`);
    if (p.description) steps.push(`  Notes: ${p.description}`);
    const fr = formatTargets("First-response", p.targets.first_response);
    const rs = formatTargets("Resolution", p.targets.resolution);
    if (fr) steps.push(`  ${fr}`);
    if (rs) steps.push(`  ${rs}`);
    if (p.escalation) steps.push(`  Escalation: ${p.escalation}`);
  }
  return {
    title: "Configure SLA policies",
    doc_links: ["https://devrev.ai/docs/product/sla", DEMO_DOC_HREF],
    steps,
  };
}

// ---------------- Email channels ----------------

export type EmailChannelInput = {
  /** Customer-facing inbound address (e.g. "support@acme.com"). */
  address: string;
  /** Optional auto-classification keywords → part name hints. */
  keyword_routing?: { keyword: string; route_to: string }[];
  /** Whether to enable auto-acknowledgement. */
  auto_acknowledge?: boolean;
};

export function emailChannelsGuidance(channels: EmailChannelInput[]): UiGuidanceSection {
  const steps: string[] = [
    "Settings → Channels → Email",
    "DevRev will assign you a forwarding address for each inbox.",
  ];
  for (const c of channels) {
    steps.push("");
    steps.push(`Inbound address: ${c.address}`);
    steps.push(
      "  Configure forwarding from your email provider to the DevRev-supplied address.",
    );
    if (c.auto_acknowledge !== false) {
      steps.push("  Enable auto-acknowledgement template for new ticket creation.");
    }
    if (c.keyword_routing?.length) {
      steps.push("  Subject/keyword routing:");
      for (const r of c.keyword_routing) {
        steps.push(`    - "${r.keyword}" → ${r.route_to}`);
      }
    }
  }
  steps.push("");
  steps.push("Outbound email — defaults that surprise customers:");
  steps.push(
    "  By default the 'From' address is the workspace, not the support agent. Replies look like they come from a generic queue.",
  );
  steps.push(
    "  In the email channel settings, enable 'use the name of the logged-in user as sender' so outbound mail shows the agent's display name and address.",
  );
  steps.push(
    "  By default 'created_by' on email-originated tickets is 'Email Integration Bot'. If the customer wants the agent to appear as the creator, configure the channel to attribute creation to the responding agent at first reply.",
  );
  return {
    title: "Configure email support channels",
    doc_links: ["https://devrev.ai/docs/product/email"],
    steps,
  };
}

// ---------------- PLuG widget ----------------

export type PlugConfigInput = {
  /** Welcome message users see when they open the widget. */
  welcome_message?: string;
  /** Hex/named color used for the widget primary brand. */
  primary_color?: string;
  /** Whether AI agent answers L1 questions before falling back to a ticket. */
  ai_agent_enabled?: boolean;
  /** Whether to fall back to creating a ticket if the AI can't resolve. */
  fallback_to_ticket?: boolean;
  /** Optional notes about KB grounding (e.g. which KB sections to use). */
  ai_grounding_notes?: string;
};

export function plugGuidance(cfg: PlugConfigInput): UiGuidanceSection {
  const steps: string[] = [
    "Settings → PLuG → Widget",
    "Copy the JavaScript snippet and add it to your site's <head> (or deploy via GTM).",
  ];
  if (cfg.welcome_message) {
    steps.push(`Set welcome message: ${JSON.stringify(cfg.welcome_message)}`);
  }
  if (cfg.primary_color) {
    steps.push(`Set primary brand color: ${cfg.primary_color}`);
  }
  if (cfg.ai_agent_enabled !== false) {
    steps.push("Enable the AI agent for L1 deflection.");
    steps.push(
      "  Ground the AI on the KB articles seeded by this blueprint (Settings → AI Agent → Sources).",
    );
    if (cfg.ai_grounding_notes) {
      steps.push(`  Notes: ${cfg.ai_grounding_notes}`);
    }
  }
  if (cfg.fallback_to_ticket !== false) {
    steps.push("Enable fallback to ticket creation when the AI cannot resolve.");
  }
  steps.push("");
  steps.push(
    "Customer-portal auth limitation: the customer-facing portal does NOT support federated login (SAML / OIDC). End users authenticate via email + magic-link only. Surface this early in the POV if the customer is expecting SSO for their end users.",
  );
  return {
    title: "Deploy the PLuG chat widget",
    doc_links: ["https://devrev.ai/docs/product/plug"],
    steps,
  };
}

// ---------------- Integrations ----------------

export type IntegrationKey =
  | "slack"
  | "jira"
  | "salesforce"
  | "freshdesk"
  | "hubspot"
  | "whatsapp"
  | "zendesk"
  | "feature_request_handler";

export type IntegrationInput =
  | IntegrationKey
  | { name: IntegrationKey; notes?: string };

const INTEGRATION_GUIDES: Record<IntegrationKey, UiGuidanceSection> = {
  slack: {
    title: "Configure Slack integration",
    doc_links: ["https://devrev.ai/docs/integrations/slack"],
    steps: [
      "Settings → Integrations → Slack",
      "Click 'Connect Slack Workspace' and authorize DevRev in the OAuth flow.",
      "Choose a default channel for ticket-event notifications.",
      "Enable bidirectional sync between Slack threads and ticket timelines.",
      "Set up the /devrev slash command for in-Slack ticket creation.",
      "",
      "Constraints to flag with the customer up front:",
      "  - Only ONE public Slack connection per DevRev org. If they have multiple Slack workspaces, pick the one the support team uses for the POV.",
      "  - Enterprise Slack accounts require DevRev Support to whitelist the OAuth app before the install will succeed. File the request with Support ahead of the demo if the customer is on Enterprise Grid.",
    ],
  },
  jira: {
    title: "Configure Jira integration",
    doc_links: ["https://devrev.ai/docs/integrations/jira"],
    steps: [
      "Settings → Integrations → Jira",
      "Provide your Atlassian Cloud URL and an API token from id.atlassian.com.",
      "Map DevRev parts → Jira projects (one-to-one is simplest for a POV).",
      "Choose which DevRev work types sync to Jira issues (typically issues, not tickets).",
      "Enable bidirectional status/comment sync.",
    ],
  },
  salesforce: {
    title: "Configure Salesforce integration",
    doc_links: ["https://devrev.ai/docs/integrations/salesforce"],
    steps: [
      "Settings → Integrations → Salesforce",
      "OAuth into your Salesforce org with admin scopes.",
      "Map Salesforce Account → DevRev account, Salesforce Contact → DevRev rev user.",
      "Decide on direction of truth: typically Salesforce is master for accounts; DevRev for ticketing.",
      "Enable opportunity sync if the POV scope includes pipeline visibility.",
    ],
  },
  freshdesk: {
    title: "Configure Freshdesk integration (parallel-run / migration)",
    doc_links: ["https://developer.devrev.ai/airsync/about"],
    steps: [
      "Settings → Integrations → Snap-ins → Install Freshdesk Airsync.",
      "Authenticate against your Freshdesk subdomain (read-only API key for parallel-run).",
      "Map Freshdesk Products → DevRev parts.",
      "Enable bidirectional ticket sync until cutover.",
      "Disable sync at cutover and import the final delta CSV.",
    ],
  },
  zendesk: {
    title: "Configure Zendesk integration (parallel-run / migration)",
    doc_links: ["https://developer.devrev.ai/airsync/about"],
    steps: [
      "Settings → Integrations → Snap-ins → Install Zendesk Airsync.",
      "OAuth into your Zendesk subdomain.",
      "Map Zendesk brands → DevRev capabilities; Zendesk groups → DevRev parts/teams.",
      "Enable bidirectional sync until cutover, then disable and import the final delta CSV.",
    ],
  },
  hubspot: {
    title: "Configure HubSpot integration",
    doc_links: ["https://devrev.ai/docs/integrations/hubspot"],
    steps: [
      "Settings → Integrations → HubSpot",
      "OAuth with a HubSpot user that has CRM access.",
      "Map HubSpot Companies → DevRev accounts; HubSpot Contacts → DevRev rev users.",
      "Choose which lifecycle stages create DevRev rev users.",
    ],
  },
  whatsapp: {
    title: "Configure WhatsApp Business channel",
    doc_links: ["https://devrev.ai/docs/integrations/whatsapp"],
    steps: [
      "Provision a WhatsApp Business API number via Meta Business Manager.",
      "Settings → Channels → WhatsApp → Connect.",
      "Provide the phone number ID and access token from Meta.",
      "Configure the welcome template that opens conversations.",
      "Enable AI agent on WhatsApp inbound (uses the same KB grounding as PLuG).",
    ],
  },
  feature_request_handler: {
    title: "Install the Feature Request Handler snap-in",
    doc_links: ["https://devrev.ai/docs/snap-ins/feature-request-handler"],
    steps: [
      "Settings → Integrations → Snap-ins → Marketplace",
      "Search for 'Feature Request Handler' and install it.",
      "Configure the trigger stage on tickets that should auto-promote to enhancements (typically 'accepted' or 'work in progress').",
      "Map the source-ticket part → target-enhancement part. The default behavior creates the enhancement under the same part as the ticket; override per part if your customer wants a separate roadmap area.",
      "Pick the visibility for the auto-created enhancement (internal vs customer-visible). Most POVs want internal until the workflow is proven.",
      "Test by transitioning one ticket into the trigger stage and confirm an enhancement is created and linked back via the timeline.",
    ],
  },
};

export function integrationsGuidance(items: IntegrationInput[]): UiGuidanceSection[] {
  return items.map((it) => {
    const key = (typeof it === "string" ? it : it.name) as IntegrationKey;
    const base = INTEGRATION_GUIDES[key];
    if (!base) {
      return {
        title: `Configure ${key}`,
        steps: [
          `No template for "${key}". Document the setup steps in your runbook before the demo.`,
          `See ${DEVELOPER_PORTAL_HREF} for snap-in / integration developer docs.`,
        ],
      };
    }
    if (typeof it === "string" || !it.notes) return base;
    return { ...base, steps: [...base.steps, "", `Customer notes: ${it.notes}`] };
  });
}

export const SUPPORTED_INTEGRATIONS = Object.keys(INTEGRATION_GUIDES) as IntegrationKey[];
